version: '3'
services:
  app_in_ubuntu:
    build: .
#    image: tennis_ball_scoreboard_project_in_ubuntu
    ports:
      - "8080:80"
    depends_on:
      - my_sql_db

  my_sql_db:
    image: mysql

    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
