version: '3.9'
services:
  app_in_ubuntu:
    build: .
    ports:
      - "8080:80"
    depends_on:
      my_sql_db:
        condition: service_started
    restart: always

  my_sql_db:
    image: mysql

    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
